### PR TITLE
Update version to 3.9.0-01

### PR DESCRIPTION
**Pull request by DarthHater**
Just bumps version to 3.9.0-01

This pull request makes the following changes:
* Modify pom
* Modify Dockerfile
* Modify README

### CODE REVIEW

**Review by joedragons — APPROVED** [review]
+1
Disclaimer: I just did a file change check, not for areas that might need to be changed but didn't.

**Comment by derjohn** [comment]
https://github.com/sonatype-nexus-community/nexus-repository-apt/issues/37 

How did you compile it ? Didn't work neither with Oracle Java 8 nor 9.

**Comment by derjohn** [comment]
```
b/src/main/java/net/staticsnow/nexus/repository/apt/internal/hosted/AptHostedComponentMaintenanceFacet.java
@@ -36,14 +36,14 @@ public class AptHostedComponentMaintenanceFacet
 {
   @Transactional(retryOn = ONeedRetryException.class)
   @Override
-  protected void deleteAssetTx(EntityId assetId) {
+  protected void deleteAssetTx(EntityId assetId, boolean deleteBlobs) {
     StorageTx tx = UnitOfWork.currentTx();
     Asset asset = tx.findAsset(assetId, tx.findBucket(getRepository()));
     if (asset == null) {
       return;
     }
     String assetKind = asset.formatAttributes().get(P_ASSET_KIND, String.class);
-    super.deleteAssetTx(assetId);
+    super.deleteAssetTx(assetId, true);
     if ("DEB".equals(assetKind)) {
       try {
         getRepository().facet(AptHostedFacet.class)
```

I have no idea what boolean deleteBlobs does in that context, but this way it compiles.

**Review by j-s-3 — APPROVED** [review]
👍

**Comment by DarthHater** [comment]
@derjohn I generally run `mvn clean package` before I commit anything, but in this case perhaps I missed it! Good catch, and I addressed that in: b260819

I'm going to follow up internally and see what exactly the nature of that change is, I imagine it just gives some flexibility to whether a delete happens just in Orient or additionally to the blobstore.

**Review by mpoindexter — APPROVED** [review]
👍

**Pull request merged**
