### PR TITLE
Make this thing work with Base, OSS and Pro

### LINKED ISSUE #41: Nexus 3.9.0-01 with 1.0.5 Failed Transition state causes Nexus to fail to restart
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
I installed 1.0.5 on Nexus 3.9.0-01 which went fine and Nexus started OK. I configured a bunch of repositories including four apt hosted repos (all repos were empty and had no artifacts, although my S3 bucket has two property files: metrics and metadata). For the GPG key, I concatted the output of the public/secret amored GPG output for the RSA signing key (no idea if thats correct or if it only wants the private key only since its not documented anywhere).

Upon restarting the Nexus service in order to expose some additional ports on the Docker container, I get the following error:

```
2018-03-09 21:24:11,088+0000 ERROR [FelixStartLevel] *SYSTEM org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl - Failed transition: NEW -> STARTED
java.lang.IllegalStateException: Missing recipe: apt-hosted
	at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
	at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.recipe(RepositoryManagerImpl.java:138)
	at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.newRepository(RepositoryManagerImpl.java:156)
	at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.restoreRepositories(RepositoryManagerImpl.java:246)
	at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.doStart(RepositoryManagerImpl.java:228)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:191)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:155)
	at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:95)
	at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:189)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1429)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
2018-03-09 21:24:11,098+0000 ERROR [FelixStartLevel] *SYSTEM org.sonatype.nexus.extender.NexusContextListener - Failed to start nexus
java.lang.IllegalStateException: Missing recipe: apt-hosted
	at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
	at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.recipe(RepositoryManagerImpl.java:138)
	at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.newRepository(RepositoryManagerImpl.java:156)
	at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.restoreRepositories(RepositoryManagerImpl.java:246)
	at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.doStart(RepositoryManagerImpl.java:228)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:191)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:155)
	at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:95)
	at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:189)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1429)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
```

Note that im also doing all of this with the S3 backend plugin.

* **What feature or behavior is this required for?**
hosted apt repo

* **How could we solve this issue? (Not knowing is okay!)**
Identify if the above bug is with apt or s3 backend plugin or the combination of both (I dont think it is S3 though, im not getting permissions errors and theres already metadata files on the bucket).

* **Anything else?**

### PR DESCRIPTION
**Pull request by DarthHater**
This changes which config files we update, such that the apt plugin will work seemlessly (hopefully) with Base, OSS and Pro flavors of Nexus Repo

This pull request makes the following changes:
* Updates `Dockerfile`
* Updates `README.md` to add new mvn requirement for core/base feature

It relates to the following issue #s:
* Fixes #41

### CODE REVIEW

**Comment by DarthHater** [comment]
@derjohn @ju2wheels this PR should make it easier to load this thing in OSS/Pro, if either of you want to take a gander.

cc @mpoindexter

**Comment by ju2wheels** [comment]
+1 building my image with this works as well.

**Review by mpoindexter — APPROVED** [review]
I guess you'd know better than me how the various feature files are organized in Nexus, but looks good to me.

**Review by j-s-3 — APPROVED** [review]
👍

**Comment by ju2wheels** [comment]
@mpoindexter Im sorry? That was absolutely rude, I was just confirming it at least works.

**Comment by DarthHater** [comment]
Thanks bruvs! @mpoindexter yeah, there's a lil known version of Nexus Repo called Base that is what you'd get if you built nexus-public. It allows me to do this kinda of trickery since OSS and PRO both inherit it's config.

**Pull request merged**
